baseURL: https://rema424.github.io/remalab/
languageCode: ja-jp
title: RemaLab
theme: anubis
publishDir: docs
enableRobotsTXT: true
hasCJKLanguage: true 
summaryLength: 0
paginate: 20

params:
  author: rema
  description: プログラミングやゲームについて日々の学びをログとして残します。
  readMore: false
  customCSS:
    - css/main.css

taxonomies:
  category: categories
  tag: tags

menu:
  footer:
    - identifier: privacy
      name: プライバシーポリシー
      title: プライバシーポリシー
      url: /info/privacy/
      weight: 0

markup:
  goldmark:
    renderer:
      unsafe: true
